### ISSUE TITLE
Preview feature is broken (possibly due to new fzf-vim releases)

### ISSUE THREAD

**Issue by 123subhadeep** [chengzeyi/fzf-preview.vim#1]
Preview feature is broken (for all commands of this plugin). 
In the preview window, always a first few lines of the file are shown. It no longer shows the matched line the preview window. You can see for yourself in the image below:

![Screen Shot 2020-08-16 at 12 51 57 PM](https://user-images.githubusercontent.com/61027055/90342730-4f46a980-dfbf-11ea-8372-3797bb4c18c4.png)

The cursor is on the first line of the search result (line 74), however in the preview window only a first few lines (lines 1-34) of the files are shown.  
I haven't debugged it, but I guess It's probably because FZF now expects a little different format.

I really love this plugin, thanks @chengzeyi for creating it ! Will be great if we can get it working again.

**Comment by chengzeyi** [comment]
Looks like that the author of `fzf` has made a breaking change of the preview functionality since 0.22.0. I will investigate more.

**Comment by 123subhadeep** [comment]
Thanks @chengzeyi  for the quick fix, I checked a few commands all of them seem to work now, except FZFQuickFix, it's still broken. Could you fix that as well. I will open a new issue for that (as I can't reopen this one). Thanks !

**Comment by 123subhadeep** [comment]
Also, in the documentation regarding preview window position (i.e. value of g:fzf_preview_window), could you change "top" to "up" as the former is invalid for the FZF plugin, i.e. "up:60%" works while "top:60%" doesn't. I had a hard time figuring that out when I installed your plugin for the first time. 

Thanks again.
