### ISSUE TITLE
In preview window, the number of lines to show before the target line should be configurable.

### ISSUE THREAD

**Issue by 123subhadeep** [chengzeyi/fzf-preview.vim#4]
So currently, all FZF preview commands (FZFMarks, FZFQuickFix, FZFBLines, etc.) show exactly 5 lines before the target line in the preview window. That value is actually hard coded (to 5) in this plugin's source code.

Can we make it configurable please ? (via a global variable may be). That way users can adjust its value manually so that the target line appears in the middle.

In my monitor, I can see around 50 lines in the preview window, showing just 5 lines before and the rest of the lines (45 lines) after the target line doesn't really help to get the best context around the target line. With that config, I can just change the value to 25.

Ideally, fzf plugin should automatically put the line in the middle. I have opened a bug for that, but it doesn't look like it will be done anytime soon. 

It will be even better if this plugin could implement automatic target line middling, but not sure how hard that will be. Making it configurable should be pretty easy.

Thanks for your support !

**Comment by chengzeyi** [comment]
I have seen that the author of `fzf` added the support for **fraction default scroll offset** while still has no clue of supporting that in `fzf.vim` plugin. I think he would add that support soon and we should be patient to wait for his demostration, rather than implement it too soon in case we face some compatibality issues later.

**Comment by 123subhadeep** [comment]
The fzf.vim plugin author has now closed the issue I created for middling the focused line: https://github.com/junegunn/fzf.vim/issues/1092

So we now just need to copy that fix here in your plugin. Thanks.

**Comment by 123subhadeep** [comment]
Actually, you didn't fix it for all commands, eg: FZFQuickFix/FZFLocList still don't have the line in the middle.
https://github.com/chengzeyi/fzf-preview.vim/commit/edb44f5c8818fff48b66f3330b8f2d58b9c3f7f5

Could you fix it for all FZF preview commands of your plugin please.
